version: 2
jobs:
  build:
    docker:
      - image: busybox

    working_directory: /src
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          command: CI_COMMIT_SHA="$CIRCLE_SHA1" make build

  deploy:
    docker:
      - image: rsync-resource

    working_directory: /src

    steps:
      - run:
          command: ls -lA && echo "Deploy step would be here"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build: {}
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
